apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: gbros-java-deployments
spec:
  selector:
    matchLabels:
      app: gbros-java
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: gbros-java
    spec:
      containers:
        - name: gbros-java
          image: gbros.0.1:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Never
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 8081 # The port that the container is running on in the clusterz
      
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-gbros-java
spec:
  selector:
    app: gbros-java
  ports:
    - protocol: "TCP"
      port: 8081 # The port that the service is running on in the cluster
      targetPort: 8081 # The port exposed by the service
  type: NodePort # type of the service.