apiVersion: v1  #k8s api version
kind: Service #k8s resource kind
metadata:
  name: gbros-java-service
spec:
  selector:
    app: gbros-java
  ports:
    - protocol: "TCP"
      port : 8080 # the port that the service is running in the cluster
      targetPort: 8080
  type: NodePort

